#!bin/bash
ls -l
total 32
drwxrwxr-x 2 vagrant vagrant 4096 Aug 21 13:51 .
drwxrwxr-x 8 vagrant vagrant 4096 Aug 21 13:25 ..
-rw-rw-r-- 1 vagrant vagrant   66 Aug 21 13:09 0-current_working_directory
-rw-rw-r-- 1 vagrant vagrant   49 Aug 21 13:10 1-listit
-rw-rw-r-- 1 vagrant vagrant   15 Aug 21 13:11 2-bring_me_home
-rw-rw-r-- 1 vagrant vagrant   17 Aug 21 13:50 3-listfiles
-rw-rw-r-- 1 vagrant vagrant    6 Aug 21 13:32 3-listfiles~
-rw-rw-r-- 1 vagrant vagrant    0 Aug 21 13:51 4-listmorefiles
-rw-rw-r-- 1 vagrant vagrant   35 Aug 21 09:42 README.md
