#!bin/bash
total 28
-rw-rw-r-- 1 vagrant vagrant   66 Aug 21 13:09 0-current_working_directory
-rw-rw-r-- 1 vagrant vagrant   49 Aug 21 13:10 1-listit
-rw-rw-r-- 1 vagrant vagrant   15 Aug 21 13:11 2-bring_me_home
-rw-rw-r-- 1 vagrant vagrant   17 Aug 21 13:50 3-listfiles
